#+title: Hobbies
#+AUTHOR: İsmail Efe Top
#+DATE: 2024-04-23
#+LANGUAGE: en
#+DESCRIPTION: Hobbies that I spend the most time for the past couple of months.

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">

I recently found myself juggling a lot of hobbies. They take up almost all of my free time and I want to talk about them. I will mention the interesting ones as I don't want to talk about “How I like to take walks” or “How I like to discover new restaurants”.

* Graphic Design

While I am not a professional, I did my fair share of design work. I designed and wrote my high school newspaper, I did Instagram posts for my department, and I did a lot of restoration work for my personal enjoyment.

I love minimalist design, there is something in it that speaks to me. Those neutral colors, big popping fonts and an inviting aura. When I approach a task I try to take away as much as I can. Only the needed should remain. In my opinion, the quote that best describes minimalist design is *“Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.”* by Antoine de Saint-Exupéry.

* Maintaining a Website

Whenever I look at a personal website that I've never seen before, I try to look for different approaches the site owner took. Like is there a navbar, is there a table of contents, what color did they used, is there javascript, etc. That is something that I never done before I had my own site. This results in a constant cycle of inspiration and evolution.

Because I don't use a generator in general sense, I have to do a lot of things by hand. Like generating RSS, generating a sitemap, optimizing pictures, SEO optimizations, fixing errors made by the [[https://pandoc.org][org to html converter]], etc. While this takes manual labor, I love it. Some people enjoy writing blog posts and some enjoy making websites, I enjoy both!

Also, if I used a blog generator, I wouldn't have learned how [[https://ismailefe.org/blog/rss/][RSS]], sitemaps, and SEO worked. I recommend everyone to learn the basics of html and css, and then host their own blog with a free service like GitHub pages!

* Visiting Flea Markets

I love wandering around flea markets, there are tons of great stuff that are dirt cheap. Old technologies that still work great, old clothes that can be made new with a quick trip to a dry cleaner, cool desk accessories, 35mm films, camera gears, and many many more.

Seeing things that were revolutionary when they first came out and talking with the people that sell them is a joy I get to experience every month. While there is a lot of good flea markets that I visit, the one I like the most is Çayyolu Antika Pazarı. I like Çayyolu because it is not as crowded as others and the things they sell are more high quality. Also most of the sellers are there to make friends and get to know new people, I like those kinds of sellers the most. Because their main goal is not to profit the most they can, their main goal is to have a good time!

While I do buy a lot of unnecessary stuff, the joy I get from talking with these people and seeing literal history makes visiting flea markets an irreplaceable hobby.

* Configuring Emacs

I spent so much time configuring this program that I could even say Emacs is my part-time job. I definitely *spend more time sharpening than cutting.*

But Emacs has become such an efficient tool that I think it *cuts* the time I spent on homework in half. It formats, converts, spellchecks, gives synonyms, translates, it manages and inserts citations, prints references, and much more. And like maintaining a site, I enjoy working on my config. Even if I didn't, I would think of it as an investment because it is a tool that I will surely be using for a really long time.

* Shooting Analog

I got into the analog world thanks to a friend more than a year ago. While I did make some mistakes that resulted in burned films, I think I learned my lesson.

I like shooting in color. My favorite film is Kodak Gold 200, the way that it captures the sunlight mesmerizes me. You can see some of the pictures I took at my [[https://ismailefe.org/photography/analog_photos/][photos page]].

Other than that I use a Agfa Optima as my main film camera. I like compact analog cameras. For me, having a big lens that you have to adjust every time defeats the purpose.

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
