#+title: The Ladder Problem
#+AUTHOR: İsmail Efe Top
#+DATE: 2024-03-13
#+LANGUAGE: en
#+DESCRIPTION: Thoughts about low-risk low-reward situations.

Last night I came across a situation that can only be described as a low-risk low-reward situation. Before I start my story, let me circle around the subject a bit.

We mostly try to be in high-reward low-risk situations. We like this situations so much that it is the number one promise the scammers and our gamble-addicted friends make. "There is a new coin in the market, it is guaranteed to go 1000x" or "There is a jockey that is guaranteed to win, it will be a cake walk". While it is important to be skeptical, if we are sure, why not take the risk. After all you have little to lose and have a lot to win.

On the contrary, we try to stay clear from the low-reward high-risk situation. Why should we risk a lot to get very little. By the way, I am not trying to take you by surprise, I am just stating the obvious. We somewhat all have ideas about either of the subjects.

But what to do about low-risk low-reward situations. These situations are so commonplace that we probably don't think about them %99 of the time. But last night I was confronted by a situation that had to be thinked about. It really put me in a hole that got deeper and deeper everytime I tried to answer a question.
