#+title: The Ladder Problem
#+AUTHOR: İsmail Efe Top
#+DATE: 2024-03-14
#+LANGUAGE: en
#+DESCRIPTION: Thoughts about low-risk, low-reward situations.

Two days ago, at midnight, I found myself in a low-risk, low-reward situation. While walking to my dormitory, I spotted a fully opened ladder on the outside of a short building that was surrounded by long trees. Because I walk that road quite often, I knew the ladder was normally folded and could only be opened with a key.

This building wasn't in a particularly beautiful area, it was a place that was design to house various classes and workshops. My first thought after seeing the ladder was, of course, to climb it but after seeing how much there was little risk and how much little reward, I decided to think more. There weren't any signs that said the ladder couldn't be climbed, there wasn't any direct cameras looking there. Also, the ladder didn't look hard to climb. It was definitely something I could climb. But should I?

After a bit more looking it felt like an unnecessary endeavor. Like I said, this building does not look at a landscape. It is an area full of buildings. But I felt like after all this thought process, I was ought to climb it.

I climbed the first bars to get a feel and got down to assess again. It was definitely something climable, as the latter was quite sturdy. But then another thought came to my mind. Why was I doing this? Doing something
