#+Language: en

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/cv/cv.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">

#+BEGIN_EXPORT html
  <div class="ust-kısım">
  <div class="name">
    <p class="name"> İsmail Efe Top
  </div>
  </div>
#+END_EXPORT

#+BEGIN_EXPORT html
<div class="contact">
  <p>Email: <a href="mailto:ismailefetop@gmail.com">ismailefetop@gmail.com</a></p>
  <p>Location: Ankara/Turkey</p>
</div>
#+END_EXPORT

* Education
-  *[2025 - Present]* Middle East Technical University - Minor Program in Logic and Philosophy of Science
  #+HTML: <p></p>

-  *[2022 - Present]* Middle East Technical University - Major Program in Foreign Language Education
  #+HTML: <p></p>
  - *CumGPA: 3,42*

-  *[2018 - 2022]* Körfez Atatürk Anatolian High School

-----
* Experiences

- *[October 2024 - Present]* Self-employed Photographer
 #+HTML: <p></p>
  - *Job Description:* Specializing in conference and portrait photography. Based in Ankara, traveling frequently to Istanbul. Providing event photography and commercial storytelling services.

- *[October 2024 - Present]* OZTOP LAB - Undergraduate Communications Assistant
 #+HTML: <p></p>
  - *Job Description:* Responsible for managing social media and project websites, designing creative materials, and transforming scientific data into accessible formats to support research initiatives for projects such as [[https://proximedprima.eu/][ProxIMed]], [[https://funtomp.com/][FunTomP]], and [[https://suchaquality.com/][SuChAQuality]].

- *[September 2019 - March 2020]* Vice President of the STEM Club of Körfez Atatürk Anatolian High School
 #+HTML: <p></p>
  - *Job Description:* Led STEM initiatives, designed posters on career opportunities, organized skill-building events, and collaborated with members to foster student engagement in STEM fields.

-----

* Volunteer
-  *[February 2025 - Present]* ODTÜMİST - Peer Mentor
  #+HTML: <p></p>
  - *Job Description:* Mentoring a peer in academic and personal development, providing guidance on coursework, resources, campus opportunities, and effective study strategies.

-  *[January 2025 - Present]* Elestirel Pedagoji - Web Developer (Part-time)
  #+HTML: <p></p>
  - *Job Description:* Web Developer and WordPress management.

-  *[November 2024 - Present]* Critical ELT Materials - Communication Coordinator
  #+HTML: <p></p>
  - *Job Description:* Creating and coordinating communication strategies and multimedia content for educational materials.

-  *[March 2024 - Present]* Middle East Technical University - Department of Foreign Language Education (Communication Coordinator)
  #+HTML: <p></p>
  - *Job Description:* Responsible for assisting the planning, creation, and dissemination of multimedia content for social media platforms, including producing short videos, designing announcement posts, and capturing event photography to enhance the online presence of the department.

- *[November 2023 - Present]* Proton - Translator
 #+HTML: <p></p>
  - *Job Description:* I am part of the Proton Localization Community. Responsible for translating all of the Proton Suite to Turkish.

- *[November 2023 - Present]* Crowdin - Translator
 #+HTML: <p></p>
  - *Job Description:* Voluntarily translating apps such as OBS, IINA, Ryujinx, and Whisky from English to Turkish via Crowdin.


-----

#+HTML: <div class="skillsandinterest">
#+HTML: <div class="skills">

* Skills
-  *Languages*

  - Turkish - Native Tongue
  - English - C2

#+HTML: <p></p><p></p>

-  *Computer Skills*

  - Wordpress
  - GNU/Linux, Git, Emacs
  - Microsoft Office programs
  - Python, Bash, HTML, and CSS
  - Photoshop and Lightroom

#+HTML: </div>
#+HTML: <div class="skills">

* Interests
-  Personal Blog Site | [[https://ismailefe.org][ismailefe.org]]
#+HTML: <p></p>

-  Open-Source Software | [[https://github.com/Ektaynot/][github.com/Ektaynot]]
#+HTML: <p></p>

-  Graphic Design | Frontend Web Design and General Photoshop Usage
#+HTML: <p></p>

-  Writing | [[https://ismailefe.org/all][ismailefe.org/all]]
#+HTML: <p></p>

-  Photography | [[https://ismailefe.org/photography][ismailefe.org/photography]]

#+HTML: </div>
#+HTML: </div>
-----
