#+Title: 5 Life Lessons
#+Author: İsmail Efe Top
#+Date: 2024-09-14
#+Language: en
#+Description: 5 life lessons from a 20-year-old.

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
#+HTML_HEAD: <link rel="manifest" href="/favicon/site.webmanifest">

I’ve been reflecting on life for the past couple of months, and my worldview has changed a lot. I feel like I have grown as a person, and I wanted to share the lessons I’ve learned during this time and throughout my life. *Here are 5 life lessons from a 20-year-old.*

* Calling an ambulance

A lot of people my age tend to question if calling an ambulance is the right thing to do when faced with health and emergency situations. I can understand the reasoning, as these kinds of situations are almost always in gray areas.

Here is a simple trick if you want to decide if you should call an ambulance; *call 911*.

If the situation escalates into you thinking you might need an ambulance, that's all the reason you need. Even if you think the situation might be minor and you think you might waste a first responder's time, you should call. Because this is what first responders are for and you won't waste anyone's time.

911 operators are trained professionals and will know what to do.

If they deem that an ambulance isn’t necessary, they will connect you to a medical professional who can guide you on what to do next and will advise you to call again if the situation worsens.

And, worst-case scenario, if you don't call 911, is the situation escalating and *someone dying*.


* "Fake it till you make it" is a powerful weapon

We humans tend to think the worst of situations. We feel like we are not good enough, feel like we don't have what it takes, and so on.

And we act accordingly to this. Whether in a work or a school setting, we find ourselves in situations where we don't want to speak up or step on anyone's toes.

We also tend to feel like we are not good enough to achieve our dreams. Hell, sometimes we don't even dare to dream.

The best way to shake off this way of thinking is to fake your ideal mindset into existence.

In my opinion, while hard and sometimes cringe, it is the best way to deal with low self-confidence and self-worth.

Think of yourself as your ideal self, work hard, speak your mind on things, and dream big. Even if you are faking it and are well aware of the fact, with time, you will turn it into reality.

* Books, textbooks, and YouTube videos

Let's say that you want to learn about investing;

Introduction to investing books/textbooks are *10 times slower* than watching a YouTube video.

But... they are *100 times* more effective.

Let me explain, if you are not watching an actual university lecture. What you are watching is a fast-paced tutorial that tries to cram as much as possible into the shortest possible amount of time.

In these kinds of videos...

- You are not able or encouraged to take notes because of its fast-paced nature.
- Rewinding is always a bother.
- And because you are not taking the lesson at your own pace, your brain may not want to absorb it.

And don't get me started on how distracting it is to learn something on YouTube where entertainment is one click away and everything else is one tab away.

Yes, reading about something can be really slow. But because you are the one deciding the pace, your brain has an easier time absorbing the information.

If buying books is becoming too expensive or cumbersome, investing in a nice e-book reader might be a great idea.

* The only person you can truly depend upon: You

Family and friends are one of the most important things in the world. You should love, cherish, and trust them. But you can't lean on them for all situations.

There will be times where you need or have to go through something on your own. These challenges tend to be hardest, and being prepared is important.

Always work and invest in yourself. People can die, material things can perish. The only person you can depend on is you. Because if you are no more, then all is done.

I also think that life has a lot more meaning when you work on yourself regularly. When you eat healthy, read, exercise, or do anything that helps you become a better person. You feel like you are more in control and the things you cannot control become more bearable.

* The only metric of success: happiness

Until this year, I thought that success would come in the form of money or fame. But it turns out I was extremely wrong.

Money doesn't mean anything if you are not happy. Fame doesn't mean anything if you are not happy. Career advancement doesn't mean anything if you are not happy.

Of course, you don't have to be happy constantly. But if you have all the things above and don't feel any happiness, then what is the point?

Everyone would choose being a happy person in a cheap car than be a sad person in a Porsche.

If material things bring you happiness, go for it. If traveling brings you happiness, travel. If being alone and doing your own thing brings you happiness, do that. Also, you don't have to do these things right now. Even dreaming about these things is a lot of fun.

In my opinion, having the people you love nearby, working on your goals and self, and having the insight to recognize what truly matters in life is the key to happiness and living a *content* life.

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
