#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- Oct 12, 2025

* What am I doing?
- I started my 5th semester. Currently in the campus library, working on the social media of a company soon to be made public.
- I recently did a photoshoot for [[https://www.instagram.com/almesostudio/][almeso]], I am really excited to showcase the results. It will be shared on my Instagram page soon. EDIT: [[https://www.instagram.com/p/DQBiJhEjJ46][link to the post]]
- I am taking Corpus Literacy for Language Professionals. It's probably the highlight of this semester. Corpus is a subject which I am deeply interested in. Being able to take this class is really a great opportunity as there is not a course similar to this in any undergraduate programs across Türkiye.
  
* What am I planning on doing?
- I have tickets for an improv theater that my friends are staring in. I really look forward to see it. 
- I want to go on photowalks. I am working in couple of jobs at the moment. Two of them I am starting this week. So my days are really taking a toll on me as I am trying to navigate this change in my schedule. I never had to chance to be "off" for a couple of hours during sunlight and thus haven't had the chance to go out and shoot.
- I want to a [[https://en.wikipedia.org/wiki/Meyhane][meyhane]] and drink [[https://en.wikipedia.org/w/index.php?title=Rak%C4%B1][rakı]] with my friends. It's been a really long time since we last went. It's a really therapeutic experience for me.
- Two of my friends are in the US at the moment. I haven't seen them all summer and they are coming back in a couple of days. I plan to have remarkable conversations with them.

* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
