#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- March 27, 2026

* What am I doing?
- I started taking photographs again, I wasn't able to shoot much ever since I got back from Japan. ([[https://glass.photo/efe][View my Japan Photographs here]])
- I enjoy writing poems a lot, while I plan to share them in the future, for now I am keeping them to myself.
- I've been watching a lot of films in the last couple of weeks. I really recommend [[https://letterboxd.com/film/one-sings-the-other-doesnt/][One Sings, the Other Doesn’t]] and [[https://letterboxd.com/film/hamnet/][Hamnet]].
  
* What am I planning on doing?
- My midterms are starting real soon, I plan to spent a couple of days in the library.
- I have two workshops coming up, I will be teaching Photography and Dissemination.
- I will be going on a photography trip pretty soon. I will leave my phone, print out the map of the area I will be visiting, and enjoy the local cuisine while taking mediocre photos.
  
* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
