#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- Sep 6, 2025

* What am I doing?
- I am currently in İzmir, I came here to join [[https://dilbilim.deu.edu.tr/conference-information/][ICTL22]], which is a conference on Turkish Linguistics. The conference ended today. It was a wonderful experience. I watched a bunch of great presentations. Hope to join the 23rd one with my own research. I hope to return to Kocaeli on the 8th. I will spend my last two days exploring the urban environment of İzmir.
- I am also taking lots of pictures. To be honest, I am having a really hard time capturing the soul of urban İzmir. I have a couple of shots I plan to share. You can see them in a couple of days on my [[https://glass.photo/efe][glass page]] and [[https://unsplash.com/@ismailefetop][unsplash page]].
- Lately my professional work has consisted of web development and video editing. While development is going well, editing is really taking a toll on me.

* What am I planning on doing?
- When I go back to Kocaeli, things are going to be a bit busy. I will spend two weeks there before going back to university. I have to balance work and family/friend time.
- Course selections will start at the end of the month. I have to do proper preparation because I have to take 4 must courses, 1 departmental elective, 1 non-departmental elective, and 2 must courses for my minor. All 8 classes must be scheduled at different times, with no overlaps.
- I want to start running again. I am waiting for going back into uni to start because there are no proper tracks for running where I live.


* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
