#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- April 30, 2025

* What am I doing?
- Things are really stale in a good way. My days are usually filled with dissemination work and photography. I try to practice acting with intent.
- Photography is the area which I feel fulfilled the most, expressing and being understood are core parts of the human experience. And for a while, photography has been how I satisfy this need.
- These days I shoot a lot of portraits. Usually with friends who volunteer.
- Currently reading [[https://www.goodreads.com/book/show/53669278-anneanne][Anneanne Sırlarını Eskitmiş Aynalar]], I would recommend it to anyone who wants to learn about the woman experience in the 20th century Türkiye.
- Today is the second year anniversary of me becoming a vegetarian. I want to celebrate it in some way.

* What am I planning on doing?
- I bought a ticket for Deniz Göktaş's comedy show. I loved [[https://letterboxd.com/film/deniz-goktas-selam-selam/][Selam Selam]], really excited to see him live.
- The exams are starting really soon; I will probably be stuck in the library for a while.
- My father wants to visit, it will be a two day visit. It's been a while since I last saw him. Excited to show him around.

* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
