#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- Sep 21, 2025

* What am I doing?
- I am currently in Kocaeli, but will go back to the campus in Ankara in a week.
- My current days are spent with hanging out with my family and doing remote dissemination work.
- I am reading [[https://myanimelist.net/manga/144267/Kaoru_Hana_wa_Rin_to_Saku][Kaoru Hana wa Rin to Saku]], it's quickly becoming my favorite romance manga. I would first recommend watching the anime and then reading the manga. I am also listening [[https://www.youtube.com/watch?v=5p5TAry-OPg][SENDEN ÇIKIŞ YOK]] on repeat, it's a really catchy song.

* What am I planning on doing?
- I have a business trip coming up in December. I can't share the exact details now but I plan to write a blog post about it.
- I have tickets to see Salih Tıraş's comedy show. I saw him open for Deniz Göktaş and he was hilarious.
- I'm really looking forward to the launch conference for APRISE, the first project I'll be helping build from the ground up. Working on a topic like alternative proteins feels great as a vegetarian.
- I really missed my friends. I will be sure to fill my days up with them.

* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
