#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- May 2, 2026

* What am I doing?
- Currently in a shuttle going to the airport, I will visit Estonia as an assistant for the [[https://enfiberconference.eu/][ENFiber International Conference]] 
- I am currently working in a large scale project about corpus linguistics. I love corpus linguistics, so it's really fun to work on it
- Related to the project, I am working on my own corpus software: [[https://topcor.org][TopCor.]]

* What am I planning on doing?
- I have a few class presentations coming up. I will have to coordinate the group work needed and do the research
- The Spring Festival is coming up in METU. I have a complicated relationship with the festival, but alas, I am really excited because I will be with my friends
- A very dear professor of mine from abroad is visiting us METU folks in the coming weeks. Really excited to spend time with her!
- A religious holiday is coming up, that means I will be with my family for a whole week! I will probably still be working remotely but doing it so in my home doesn't sound so bad.

* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
