#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- Jun 9, 2026

* What am I doing?
- I am currently taking a break from studying for my finals.
- I started developing an iOS game, learning a lot from the whole process. The app will hopefully be out in a few weeks.
- I've also been dabbling with interacting with LLM's through the API. I am learning a lot of basics that I missed learning.
- I am reading [[https://www.goodreads.com/book/show/57443844-i-mkans-z-a-lar-ve-di-er-yaz-lar][O Sırada 2]], this is the best book series ever.
  
* What am I planning on doing?
- I have a bus trip coming up, and I will visit a couple of countries from Europe. I am really excited about it.
- I will be joining the [[https://www.birmingham.ac.uk/events/corpus-linguistics-summer-school-2026][Corpus Linguistics Summer School 2026]], I am really excited about this school/course. There aren't many corpus-related programs, so finding a one like this makes me really excited.
  
* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
