#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- Nov 20, 2025

* What am I doing?
- I am in the middle of a midterm period, so I am studying regularly for my major and minor.
- I am preparing for my trip overseas, I will go in two weeks. Quite excited to travel and see a place I've never been before.
- We are planning a Winter Social Sciences Camp in [[https://en.wikipedia.org/wiki/Middle_East_Technical_University_Northern_Cyprus_Campus][METU Cyprus Campus]], I am responsible for photography there. I am doing some pre-planning and shooting some promos.
     
* What am I planning on doing?
- I plan to take great photos in my overseas trip and in Cyprus. I like discovering places through the lens. 
- I am working on a corpus linguistics tool. I plan to fully launch it one day.

* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
