#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- Sep 21, 2026

* What am I doing?
- I started a wine review section for this blog. So far, I have reviewed only two wines. It's a really fun hobby, and I am learning a lot about grapes, wine, winemaking. It's relatively cheap because I only buy the least expensive stuff I can find. Because I want this hobby to be a long-term one, I am okay with gradually getting into more expensive wines as I advance in my career and have more money to spend on hobbies.
- I am currently reading [[https://www.goodreads.com/en/book/show/205363955-meditations-for-mortals][Meditations for Mortals]] and [[https://www.goodreads.com/book/show/199525652-hirayasumi-vol-1][Hirayasumi]]. Meditations for Mortals is the best "self-help" book I've read. It is realistic and I think it helps you form long-lasting habits because it doesn't tell you what to do. Instead it puts you in a place where you make the decisions. Hirayasumi is one of the best manga I've read in a while. Its art style is gorgeous and its story is really wholesome. I would definitely recommend both.
- I've been getting into Balatro again. It's a really fun game and there are a lot of metas. Playing with different decks and doing challenges keeps the game fresh for me.
    
* What am I planning on doing?
- New semester is starting next week. I am really excited to get back to my courses and see my friends who have been away for far too long.
- As this will be my final year, I will be a student teacher at a public school for the year. This will be my first experience teaching English. I am both nervous and excited.
  
* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
