#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- July 23, 2025

* What am I doing?
- I came back to Kocaeli. Living a peaceful life.
- My lab and faculty projects have been really active lately, that's why I've been doing a lot of remote work.
- I usually do my remote work from home, but I occasionally go to Kadıköy to work. My favorite cafe, Walter's, is there and doing remote work from a cafe brings variety to my work life.
- Going to Kadıköy and Moda is a lot of fun. There are tons of vegan restaurants and great sights to photograph. There are also a lot of culture activities, but I am not attending them as much as I want.
- I started to go to the cinema again. There is a chain cinema that is in walking distance. They usually show old classic movies in addition to new releases.

* What am I planning on doing?
- I want to finish the final project I am doing for the faculty. It will take around 1 week. I have to work in a virtual machine for this project and the sluggishness is really getting to me. But it's coming together really nicely. I am proud of the work me and the team has put in.
- I plan to visit Mersin and İzmir this summer.

* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
