#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- Aug 24, 2026

* What am I doing?
- This summer, I enrolled in summer school. I thought taking a course from a year above could lessen my workload, as completing a philosophy minor alongside my major is quite challenging.
- I've been doing a lot of catching up with old friends. Sometimes, finding a time that works for both parties can be difficult, but in the end, it's very much worth it, as spending time with someone I haven't seen in a long time is one of the best feelings there is.
- I try to find interesting photography projects. They are mostly disasters, but I find joy in disasters because, even though I am fairly new to photography (about four years), I am quite bored with chasing the “perfect photograph” that everyone seems to pursue. I am doing lots of experiments and happily failing a lot.
   
* What am I planning on doing?
- I am doing a lot of cooking at the moment but not quite at the level that I would have liked. I want to get into vegan recipes. The first recipe I want to try is a Glazed Tofu with Rice, something like [[https://supperinthesuburbs.com/2026/01/28/soy-glazed-tofu-with-rice-and-peas/][this]]. I want to try a bunch of different recipes, so if you have any recipe recommendations, feel free to [[mailto:ismailefetop@gmail.com][e-mail me]].
- It has been a while since I last did a portrait photoshoot. I want to do a themed portrait photoshoot.
- I want to get into the tea hobby, but I think winter would be a better time to start as it's really hot in Ankara right now!

* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
