#+title: Now

#+LANGUAGE: en

#+HTML_HEAD: <meta name="description" content="Learn about what I am doing" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">


If you don't know what a now page is, check out [[https://nownownow.com/about][this website]].

* When did I last update this page
- Mar 1, 2025

* What am I doing?
- I started doing a minor in Logic and Philosophy of Science, it's going really well but my academic load increased a lot. That's why I've been visiting the library everyday to study.
- I am reading [[https://www.goodreads.com/book/show/390606.Philosophy_of_Science_in_the_Twentieth_Century][Philosophy of Science in the Twentieth Century: Four Central Themes by Donald Gillies]]
- I've been doing web design for [[https://criticaleltmaterials.org/][Critical ELT Materials]] and [[https://elestirelpedagoji.org][Eleştirel Pedagoji]]
- I started taking French lessons, I am doing my best to learn vocab and grammar.

* What am I planning on doing?
- I will shoot a convention this week, really excited for it. It's been a while since I last did a shoot for a convention.
- Philosophy is a subject I am passionate about. I plan on reading a lot more about the Philosophy of science.

* Archive
#+begin_export html
<p>I also have a page dedicated to my old Now pages. You can check it out here, <a href="/now/archive/">Now Archive Page</a>.</p>
#+end_export

#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
