#+title: My Top Album Picks For 2023
#+AUTHOR: İsmail Efe Top
#+DATE: 2024-01-18
#+LANGUAGE: en
#+HTML_HEAD: <link rel="webmention" href="https://webmention.io/ismailefe.org/webmention" />
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
#+HTML_HEAD: <link rel="manifest" href="/favicon/site.webmanifest">
2023 might be my busiest year yet. As a first-year in my major, I'm discovering a new city, giving tons of presentations, and balancing my relationships. As a result, I've had less time to discover and enjoy new music.

In spite of this I found lots of good record to listen to. Here are my top picks of 2023.

/this listing is in no particular order./

* 1. SCARING THE HOES
Until the  announcement of this album I've have never heard of Danny Brown. And honestly, I didn't care who he was, because I knew that if JPEGMAFIA was one of the co-artists of this project, it would be good. When the first song 'lean beef patty' came out, I knew I was right.

But I have to be honest, this album is not for everyone. It has a rough and dirty sound. Lots of beat switches and samples that are straight from a forgotten graveyard. But these are the exact reasons why I love this album so much. This album is your weird friend that always do niche movie references and that joke about internet memes. When done is dose, which SCARING THE HOES does, it feels like a different and fun thing.

* 2. Let's Start Here.
I always knew Lil Yachty as a lighthearted rapper. So, when I heard that he had made a Psychedelic Rock album, I knew I had to check it out.

On my first listen, the Pink Floyd influence was pretty apparent but there was something different. His sound was fun, catchy and like how a Psychedelic Rock should be; it was /trippy/. And the album stayed that way, it was fresh every time I listened to it. That's why I spend the quarter of my year listening to this album.

* 3. UTOPIA
Utopia is an album in which Travis Scott tries to return to his roots. It features raw cuts and a plethora of different voices.

This album was in the making for about 4 years. And you can tell this by how polished it is. Also, there are 52 beat switches in the album. So, every song feels like you are listening to an [[https://en.wikipedia.org/wiki/Extended_play][EP]].

* 4. LATIN VIRGIN
This is a Turkish release, and one of my favorites. The reason why I love this album so much is that it's a big milestone for the Turkish rap scene. For a really long time the scene was populated by people who claim that woman weren't able to make good rap tracks and those few who made good rap tracks were people who were very conservative of their bodies. Alizade showed that you don't have to hide your body to make good rap song. While her songs lack in the lyrics department she more than makes up for it by using different types of sounds and colorful beats in her songs.

While she is still criticized in Turkey for showing off her body and not being a proper /'lyricist'/, I admire what she is bringing to the table in the Turkish rap scene.

* 5. For All The Dogs
I feel like Drake's albums are really a hit or miss. And luckily this album is a hit. While this album could cook a bit more, I like how raw it is. There are bunch of features I really like and it is a fun album.

He really needs to not take himself so seriously, he shines best when he has fun too.
