#+title: How to give good presentations
#+AUTHOR: İsmail Efe Top
#+DATE: 2024-02-23

#+HTML_HEAD: <meta name="description" content="Learn how to give good presentations">
#+LANGUAGE: en

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">

#+HTML_HEAD: <style> li {padding-bottom: 6px;} </style>

In my department we give a lot of presentations, so mastering the skill is important for a student like me. I learned a lot in my last 2 years at metu and I want to share what I learned.

This guide will include tips about time management, physical environment, styling of the slides and other general information.

* General
My first tip would be to *always have an introduction*. Introductions are important because they help the listener have a short sense of what you are talking about. Diving into a subject without the proper introduction can lead to a sense of confusion in the listener.

In your introduction you can talk about...
- General information about your subject
- Why you chose that particular subject
- Significance and relevance of the subject
- The key takeaways listeners can expect by the end of the presentation

While it may seem obvious, thanking the listeners at the end is very important. We should remember that while we do spend time preparing, they also spend their time listening to us.


* Physical Environment
If you are not giving a presentation in a space designed for it, going into there beforehand and removing any distractions can be helpful. For example, if you are going to give a presentation in a class or a meeting room, adjusting the curtains and cleaning the whiteboard can help listeners not lose focus.

A lot of presenters hide behind a podium. While it can help when you feel anxious, it can also lower your presence as a presenter. I would suggest not putting anything in front of you and trying to be as close as possible to the audience without going into their personal space. Maintaining good space and leaning closer when announcing a heading is a good strategy to stress the importance of that portion. Other than that, you should *never put your hands in your pocket*. Letting the audience see your hand fully is always important.

* Presentation Slides
First of all, any presentation software works. I use and recommend [[https://pitch.com][pitch]]. The most important thing when presenting a stylish slide is the font and simplicity. Let me explain more.

Most people try to cram all the information they can into their slides. This leads to presentations that look like textbooks. I think that is the biggest sin you can commit. This is a big mistake because the presenter is the one giving information not the slide. Slides should complement you, not replace you. Another reason we shouldn't make slides with a lot of text is that they are distracting. While you try to talk about your subject, the audience will look and try to read what is on the slide. If you MUST put a lot of text or a big picture, you should at least give proper time for the audience to look at the slide properly.

Another mistake I see is that making your background too crowded, this makes it hard to read or see whats on the slide. I would suggest a single color background with small graphics that are away from the center. Another thing to note is the contrast between the color of your background and the color of your text. If they don't have good contrast, the text might be too hard to read. Having good contrast is especially important because while your colors might look good on your fancy computer screen, they might blend together on the projector due to low color performance. So having a little bit more of a headroom can be a good idea.

Lastly, using short and simple animations between your slides can be a good visual sign of professionalism.

* Time Usage
To be honest, I think this is the most important part. The usage of your time dictates how people remember your presentation. If it is too long, people can get bored and stop listening to you. And if it is too short, people might think that you were unprepared. One of my instructors has a great advice on this, he says "When preparing for a presentation, aim for the 9/10 of the time allocated to you.". It is a common practice to time yourself when preparing. But if you try to make your presentation stretch to the time given to you, you will see that it will always be longer when doing the actual presentation. With this advice, you can make your speech more to the point and easier to follow.

Addition to this, I would suggest finishing your presentation a couple of minutes early. In my opinion this can give a sense of professionalism and competence. It is definitely better than finishing late. Just make sure that it is no more than 5 minutes.

* To conclude...
- Do an introduction about the subject
- Thank the audience for their time at the end
- Declutter your presentation environment
- Make your body and hands visible
- I recommend using pitch for your slides
- Do not cram text into slides
- Make your slide backgrounds simple
- Most of the time a single color background is perfect
- Have good contrast between your background and text
- Use fast and simple transitions
- When preparing aim for the 9/10 of the time allocated to you
- Try to finish a couple of minutes early


#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
