#+TITLE: Writing Tools
#+AUTHOR: İsmail Efe Top
#+DATE: 2024-07-12
#+LANGUAGE: en
#+DESCRIPTION: A list of the tools I use to connect my mind to the physical world.

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
#+HTML_HEAD: <link rel="manifest" href="/favicon/site.webmanifest">

I love writing, it helps me empty my mind and improve my ability to express myself. While I enjoy writing digitally the most, I have to write to a paper often because of school and other circumstances.

I have a few friends that accompany me while I write. I acquired these friends throughout my life, each has their own unique stories and reasons. They make writing easy and fun for me. I will introduce them chronologically.

* Rotring 500

If you want to learn more you can [[https://ismailefe.org/blog/rotring500/][check out my previous post]] where I talked about this pen in more detail.

This is a pen I bought by chance when I was preparing for university exam. I solved everything with that pen. It is lightweight but has a nice build quality. While it is cheap, it doesn't feel like it. When I first saw that pen I fell in love with it's pure black color and it's italic red font.

When I look at it objectively, it may not be the most ergonomic pen, but I enjoy using it so much that any discomfort from writing for long hours doesn't bother me a bit. I usually notice it after I am done writing.

I also used it a lot during my preparation year at university and my first year. I entered all of my exams with it and always carried it with me. I still use it from time to time but my newly bought Rotring 800 became the main mechanical pencil I use.

I recommend it to everyone who wants a good-looking mechanical pencil that is light and long lasting.

* Pensan Büro


While I haven't seen this pencil anywhere other than Türkiye, it is probably the most popular pencil here. It is a dirt cheap ballpoint pend that is usually blue. Every Turkish person probably used it at some point in their life. I can't stress this enough this particular pen is sold and used everywhere. From government offices to sports-books.

In addition to it's availability there is another big reason, this thing SLIDES. It is so smooth to write on. I use a ballpoint pen when I want to go crazy. Creating diagrams, writing bold questions and sketching solutions. The main point it writing ideas fast. And this pen is the best when it comes to being fast.

It is really light and has a pen clip. You can attach it's cap to it's back and extend it. Why would you need anything else?

* HHKB Professional BT

I was really into custom keyboards from 2019 to 2023. I would follow custom keyboard youtubers and subreddits. I would listen to tons of typing tests and would dream of "end-game" keyboards like Keycult and TGR. Luckily the dollar exchange rate was somewhat stable when I started the hobby and I got the change to try a lot of custom boards and switches. While I did try a lot of different mechanical keyboards there was a one keyboard that I wasn't able to try. It was a keyboard called HHKB and it didn't have mechanical switches. It used a patented electrostatic capacitive Topre switches. These switches were produced by Topre Corporation in Japan and didn't seem to have a counterfeit alternative.

These switches were used by a couple of different keyboard brands. The most popular one is the HHKB and they were praised as the ultimate keyboards because of their 'godly feel' and layout. There were a lot of custom keyboards that used the HHKB layout. You can learn more about the HHKB layout in [[https://hhkeyboard.us/blog/hhkb-layout#what][HHKB's official blog post]].

Another characteristic of a HHKB keyboard is how expensive they are, especially in countries that don't have a official distributor because of the heavy import fee.

For a really long time I searched local second hand sites for one and finally found it in Jan 2023. I bought it from a foreign guy that bought it a couple of years before in his trip to Japan. He sold it to me for a fair price and I finally had a HHKB keyboard.

Was it as good as people deemed it to be? Yes it was. The keys felt heavenly and the layout was great. I retired my custom keyboards and used HHKB primarily. While I wasn't able to carry it with me outside, it felt special every time I typed on it. I loved that thing.

After using it for a year I sadly developed carpal tunnel syndrome. I would get heavy wrist pain after a couple of minutes of using it. Even though it saddens me I had to stop using my HHKB.

* Logitech Wave Keys

While I was researching ergonomic keyboards like [[https://github.com/foostan/crkbd][The Corne]] and [[https://ergodox-ez.com/][Ergodox Ez]] I came across Logitech Wave Keys. Honestly this keyboard wasn't my first choice. But because it was tenth the price of the other keyboards I was looking at I had no other real choice. I bought it second hand and waited.

When I first started typing I was honestly quite surprised as it felt similar to my HHKB. I was really large and the keys were more flat and low-profile.

This keyboard's main selling point is it's wave pattern across it's keys. It is suppose to help people who suffer from wrist pain or people who spend a lot of time in front of desk.

To my surprise it almost completely eliminated my wrist and hand pain. It also felt great to type on. It honestly saved me from spending a ton of money on a split keyboard I had to import and pay additional taxes on.

* Conclusion

While some of these got replaced, they will be tools that I cherish for the rest of my life. I see them all as milestones that helped me in various ways.

Ironically I wrote this post with my laptop's keyboard. This is the case for a lot of my posts as I like to write outside. I did not include my laptop's keyboard because it isn't anything special or trivial. Also, being mindful of when I use my beloved tools makes using them a special event.

Thanks a lot for reading so far. It has been a lengthy post that I enjoyed writing. Feel free to email me if you want to share your writing tools or anything else. I love getting emails from humans!


#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
