#+TITLE: My Writing Tools
#+AUTHOR: İsmail Efe Top
#+DATE: 2024-07-12
#+LANGUAGE: en
#+DESCRIPTION: A list of the tools I use to connect my mind to the physical world.

#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/templates/style.css" />
#+HTML_HEAD: <meta name="theme-color" content="#fffcf0">
#+HTML_HEAD: <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
#+HTML_HEAD: <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
#+HTML_HEAD: <link rel="manifest" href="/favicon/site.webmanifest">

I love writing, it helps me empty my mind and improve my ability to express myself. While I enjoy writing digitally the most, I have to write to a paper often because of school and other circumstances.

I have a few friends that accompany me while I write. I acquired these friends throughout my life, each has their own unique stories and reasons. They make writing easy and fun for me. I will introduce them chronologically.

* Rotring 500

If you want to learn more, you can [[https://ismailefe.org/blog/rotring500/][check out my previous post]] where I talked about this pen in more detail.

This is a mechanical pencil that I bought by chance when I was preparing for university exam. I solved every test, mock exam, and problem with this pen. It is lightweight but has a nice build quality. While it is cheap, it doesn't feel like it. When I first saw this pen I fell in love with it's pure black body and it's italic red font.

When I look at it objectively, it may not be the most ergonomic pen, but I enjoy using it so much that any discomfort from writing for long hours doesn't bother me a bit. I usually notice the fatigue in my wrists after I am done writing.

I also used it a lot during my preparation year at university and my first year. I entered all of my exams with it and always carried it with me. I still use it from time to time but my newly bought Rotring 800 became the primary mechanical pencil I use.

I recommend it to everyone who wants a good-looking mechanical pencil that is light and long lasting.

* Pensan Büro

While I haven't seen this pencil anywhere other than Türkiye, it is probably the most popular pencil here. It is a dirt cheap ballpoint pend that is usually in blue color. Every Turkish person probably used it at some point in their life. I can't stress this enough, this particular pen is sold and used everywhere. From government offices to sports-books.

In addition to it's availability, there is another big reason, this thing SLIDES. It is so smooth to write on any surface.

I use a ballpoint pen when I want to go crazy. Creating diagrams, writing questions in bold and sketching solutions. My main goal is writing ideas fast. And this pen is the best when it comes to that.

It is also really light and has a pen clip. You can attach it's cap to it's back and extend it. What else can you want from a pen?

* HHKB Professional BT

I was really into custom keyboards from 2019 to 2023. I would follow custom keyboard youtubers and subreddits. I would listen to tons of typing tests and would dream of "end-game" keyboards like Keycult and TGR.

Luckily the dollar exchange rate was somewhat stable when I started the hobby and I got the chance to try a lot of custom boards and switches. While I did try a lot of different mechanical keyboards, there was a one keyboard that I wasn't able to try. It was a keyboard called Happy Hacking Keyboard (HHKB) and unlike all of the keyboards I used in the past, it didn't have mechanical switches. Instead, it used a patented electrostatic capacitive Topre switch. These switches were produced by Topre Corporation in Japan and didn't seem to have a counterfeit alternative that I could order from Aliexpress to try.

These switches were used by a couple of different keyboard brands. The most popular one was the HHKB and they were praised as the ultimate keyboard because of their 'godly feel' and the layout. There were a lot of custom keyboards that used the HHKB layout. You can learn more about the HHKB layout in [[https://hhkeyboard.us/blog/hhkb-layout#what][HHKB's official blog post]].

Another characteristic of a HHKB keyboard is how expensive they are. The base model's price starts at 300 dollars and they are especially expensive in countries that don't have a official distributor because of the heavy import fee.

For a really long time I searched local second-hand sites for one and finally found it in Jan 2023. I bought it in person from a foreign guy that bought it a couple of years before, in his trip to Japan. He sold it to me for a fair price and I finally had a HHKB keyboard.

Was it as good as people deemed it to be? Yes, it was. The keys felt heavenly and the layout was great. I retired my custom keyboards and used the HHKB primarily. While I didn't carry it with me everywhere, it felt special every time I had the chance to type on it. I loved that thing.

After using it for a year I sadly developed carpal tunnel syndrome. I would get heavy wrist pain after a couple of minutes of using it. Even though it saddens me, I had to stop using it.

* Logitech Wave Keys

While I was researching ergonomic keyboards like [[https://github.com/foostan/crkbd][The Corne]] and [[https://ergodox-ez.com/][Ergodox Ez]], I came across [[https://www.logitech.com/en-us/products/keyboards/wave-keys-ergonomic-wireless.920-011898.html][Logitech Wave Keys]]. To be honest, this keyboard wasn't my first choice. But because it was tenth the price of the other keyboards I was looking at, I had no other real choice. I bought it second-hand and waited.

When I first started typing, I was honestly quite surprised as it felt similar to my HHKB. It was really large and the keys were dome-like and low-profile.

This keyboard's main selling point is it's wave pattern across it's keys. It's suppose to help people who suffer from wrist pain and people who spend a lot of time in front of a desk.

To my surprise, it almost completely eliminated my wrist and hand pain. It also felt great to type on. It honestly saved me from spending a ton of money on a split keyboard that I would have to import and pay additional taxes on.

* Conclusion

While some of these got replaced, they will always be tools that I cherish. I see them all as milestones that helped me in numerous ways.

Ironically, I wrote this post with my laptop's keyboard. This is the case for a lot of my posts as I like to write outside. I did not include my laptop's keyboard because it is trivial and isn't anything special. Also, being mindful of when I use my beloved tools makes using them more special.

Thanks a lot for reading. It has been a lengthy post that I really enjoyed writing. Feel free to email me if you want to share your writing tools or anything else. I love getting emails from humans!


#+BEGIN_EXPORT html
<div class="bottom-header">
  <a class="bottom-header-link" href="/">Home</a>
  <a href="mailto:ismailefetop@gmail.com" class="bottom-header-link">Mail Me</a>
  <a class="bottom-header-link" href="/feed.xml" target="_blank">RSS</a>
  <a class="bottom-header-link" href="https://github.com/Ektaynot/ismailefe_org" target="_blank">Source</a>
</div>
<div class="firechickenwebring">
  <a href="https://firechicken.club/efe/prev">←</a>
  <a href="https://firechicken.club">🔥⁠🐓</a>
  <a href="https://firechicken.club/efe/next">→</a>
</div>
#+END_EXPORT
