name: Python Script

on:
  push:
    branches:
      - master  # Adjust this branch according to your repository

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Run script
        run: python /home/runner/work/ismailefe_org/ismailefe_org/etc/rss_builder/rss.py
